config/routes.rb
Rails.application.routes.draw do
  resources :watches
  resources :laptops
  resources :smartphones
  resources :instruments
  resources :store
  devise_for :users, controllers: {
  	registrations: 'registrations'
  }
  get "/instrument_brand_ibanez", to: "instruments#instrument_brand_ibanez", as: "instrument_brand_ibanez"
  get "/instrument_brand_gibson", to: "instruments#instrument_brand_gibson", as: "instrument_brand_gibson"
  get "/instrument_brand_epiphone", to: "instruments#instrument_brand_epiphone", as: "instrument_brand_epiphone"
  get "/instrument_brand_dean", to: "instruments#instrument_brand_dean", as: "instrument_brand_dean"
  get "/instrument_brand_fender", to: "instruments#instrument_brand_fender", as: "instrument_brand_fender"


  get "/instrument_price_0_1000", to: "instruments#instrument_price_0_1000", as: "instrument_price_0_1000"
  get "/instrument_price_1000_2000", to: "instruments#instrument_price_1000_2000", as: "instrument_price_1000_2000"
  get "/instrument_price_2000_3000", to: "instruments#instrument_price_2000_3000", as: "instrument_price_2000_3000"





  get "/smartphone_brand_huawei", to: "smartphones#smartphone_brand_huawei", as: "smartphone_brand_huawei"
  get "/smartphone_brand_apple", to: "smartphones#smartphone_brand_apple", as: "smartphone_brand_apple"
  get "/smartphone_brand_samsung", to: "smartphones#smartphone_brand_samsung", as: "smartphone_brand_samsung"
  get "/smartphone_brand_oppo", to: "smartphones#smartphone_brand_oppo", as: "smartphone_brand_oppo"
  get "/smartphone_brand_xiaomi", to: "smartphones#smartphone_brand_xiaomi", as: "smartphone_brand_xiaomi"


  get "/smartphone_price_0_250", to: "smartphones#smartphone_price_0_250", as: "smartphone_price_0_250"
  get "/smartphone_price_250_500", to: "smartphones#smartphone_price_250_500", as: "smartphone_price_250_500"
  get "/smartphone_price_500_1000", to: "smartphones#smartphone_price_500_1000", as: "smartphone_price_500_1000"


  root 'store#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    @instruments = Instrument.all.order("created_at desc")
    @smartphones = Smartphone.all.order("created_at desc")
    @laptops = Laptop.all.order("created_at desc")
    @watches = Watch.all.order("created_at desc")

  end
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/store/_panel.html.erb
<nav class="panel">
  <p class="text pv1 f6" style="font-size: 20px">FILTER</p>

  <ul class="mb3 pa0" style="float: left; display: flex; margin: 0 auto">
    <li class="pv1" style="margin-left: 10px">
      <%= link_to 'All', "#", class: "button is-fullwidth is-dark" %>
    </li>

    <li class="pv1" style="margin-left: 10px">
      <%= link_to 'Instruments', instruments_path, class: "button is-fullwidth is-primary" %>
    </li>

    <li class="pv1" style="margin-left: 10px">
      <%= link_to 'Smartphones', smartphones_path, class: "button is-fullwidth is-link" %>
    </li>

    <li class="pv1" style="margin-left: 10px">
      <%= link_to 'Laptops', "#", class: "button is-fullwidth is-warning" %>
    </li>

    <li class="pv1" style="margin-left: 10px">
      <%= link_to 'Bycicles', "#", class: "button is-fullwidth is-info" %>
    </li>
  </ul>
  <hr style="width: 1%">
</nav>

app/views/store/index.html.erb
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Sell your used goods here!
      </h1>
    </div>
  </div>
</section>
<% end %>


<!-- Panel Section -->
<div class="columns" style="margin-top: 15px">
  <div class="column">
    <li class="pv1" style="list-style: none">
      <%= link_to 'All', root_path, class: "button is-fullwidth is-dark" %>
    </li>
  </div>
  <div class="column">
    <li class="pv1" style="list-style: none">
      <%= link_to 'Instruments', instruments_path, class: "button is-fullwidth is-primary" %>
    </li>
  </div>
  <div class="column">
    <li class="pv1" style="list-style: none">
      <%= link_to 'Smartphones', smartphones_path, class: "button is-fullwidth is-link" %>
    </li>
  </div>
  <div class="column">
    <li class="pv1" style="list-style: none">
      <%= link_to 'Laptops', laptops_path, class: "button is-fullwidth is-success" %>
    </li>
  </div>
  <div class="column">
    <li class="pv1" style="list-style: none">
      <%= link_to 'Watches', watches_path, class: "button is-fullwidth is-info" %>
    </li>
  </div>
</div>






<div class="smartphone-index-grid pt4">
  <% @smartphones.each do |smartphone| %>

    <div class="smartphone border-light">
      <div class="smartphone-thumb">
      <%= link_to image_tag(smartphone.image_url(:thumb)), smartphone %>

      <% if smartphone.condition? %>
        <div class="condition">
          <span class="tag is-dark"><%= smartphone.condition %></span>
        </div>
      <% end %>
      </div>


    <div class="pa3">

      <h3 class="fw7 f4 title"><%= link_to smartphone.title, smartphone %></h3>

      <p class="has-text-gray fg pt1">Sold by <%= smartphone.user.name %></p>

      <p class="f3 fw6 has-text-right pt2 price"><%= number_to_currency(smartphone.price) %></p>

      <% if smartphone_author(smartphone) %>
         <%= link_to 'Edit', edit_smartphone_path(smartphone), class: "button is-small" %>
         <%= link_to 'Delete', smartphone, method: :delete, data: { confirm: "Are you sure ?" }, class: "button is-small" %>

      <% end %>
      <span class="tag is-dark">Mobile</span>

    </div>
  </div>
  <% end %>
  
</div>


<div class="instrument-index-grid pt4">
  <% @instruments.each do |instrument| %>

    <div class="instrument border-light">
      <div class="instrument-thumb">
      <%= link_to image_tag(instrument.image_url(:thumb)), instrument %>

      <% if instrument.condition? %>
        <div class="condition">
          <span class="tag is-dark"><%= instrument.condition %></span>
        </div>
      <% end %>
      </div>


    <div class="pa3">

      <h3 class="fw7 f4 title"><%= link_to instrument.title, instrument %></h3>

      <p class="has-text-gray fg pt1">Sold by <%= instrument.user.name %></p>

      <p class="f3 fw6 has-text-right pt2 price"><%= number_to_currency(instrument.price) %></p>

      <% if instrument_author(instrument) %>
         <%= link_to 'Edit', edit_instrument_path(instrument), class: "button is-small" %>
         <%= link_to 'Delete', instrument, method: :delete, data: { confirm: "Are you sure ?" }, class: "button is-small" %>

      <% end %>
      <span class="tag is-primary">Guitar</span>

    </div>
  </div>
  <% end %>
  
  
</div>




<div class="laptop-index-grid pt4">
  <% @laptops.each do |laptop| %>

    <div class="laptop border-light">
      <div class="laptop-thumb">
      <%= link_to image_tag(laptop.image_url(:thumb)), laptop %>

      <% if laptop.condition? %>
        <div class="condition">
          <span class="tag is-dark"><%= laptop.condition %></span>
        </div>
      <% end %>
      </div>


    <div class="pa3">

      <h3 class="fw7 f4 title"><%= link_to laptop.title, laptop %></h3>

      <p class="has-text-gray fg pt1">Sold by <%= laptop.user.name %></p>

      <p class="f3 fw6 has-text-right pt2 price"><%= number_to_currency(laptop.price) %></p>

      <% if laptop_author(laptop) %>
         <%= link_to 'Edit', edit_laptop_path(laptop), class: "button is-small" %>
         <%= link_to 'Delete', laptop, method: :delete, data: { confirm: "Are you sure ?" }, class: "button is-small" %>

      <% end %>
      <span class="tag is-success">Laptop</span>

    </div>
  </div>
  <% end %>
  
  
</div>



<div class="watch-index-grid pt4">
  <% @watches.each do |watch| %>


    <div class="watch border-light">
      <div class="watch-thumb">
      <%= link_to image_tag(watch.image_url(:thumb)), watch %>

      <% if watch.condition? %>
        <div class="condition">
          <span class="tag is-dark"><%= watch.condition %></span>
        </div>
      <% end %>
      </div>


    <div class="pa3">

      <h3 class="fw7 f4 title"><%= link_to watch.title, watch %></h3>

      <p class="has-text-gray fg pt1">Sold by <%= watch.user.name %></p>

      <p class="f3 fw6 has-text-right pt2 price"><%= number_to_currency(watch.price) %></p>

      <% if watch_author(watch) %>
         <%= link_to 'Edit', edit_watch_path(watch), class: "button is-small" %>
         <%= link_to 'Delete', watch, method: :delete, data: { confirm: "Are you sure ?" }, class: "button is-small" %>

       <% end %>
      <span class="tag is-info">Watch</span>

    </div>
  </div>
  <% end %>
 
  
</div>